import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  layout: { minHeight: '100vh', display: 'flex', flexDirection: 'column' },
  header: {
    padding: '24px 24px 16px',
    borderBottom: '1px solid var(--border)',
    background: 'var(--surface)',
  },
  headerTop: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 12,
  },
  title: { margin: 0, fontSize: '1.5rem', fontWeight: 700, letterSpacing: '-0.02em' },
  subtitle: { margin: '8px 0 0', fontSize: 14, color: 'var(--text-muted)', maxWidth: 720 },
  headerActions: { display: 'flex', alignItems: 'center', gap: 12 },
  link: { color: 'var(--accent)', fontSize: 14 },
  toolbar: { marginTop: 16, display: 'flex', flexDirection: 'column', gap: 12 },
  toolbarFirstRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  platformGroup: { display: 'flex', gap: 6 },
  platformOption: {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '10px 16px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border)',
    background: 'var(--surface-hover)',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    fontSize: 14,
    minHeight: 44,
  },
  idsLabelInline: {
    marginLeft: 'auto',
    fontSize: 13,
    color: 'var(--text-muted)',
    cursor: 'pointer',
  },
  label: { display: 'flex', flexDirection: 'column', gap: 6 },
  labelText: { fontSize: 13, color: 'var(--text-muted)' },
  textarea: {
    width: '100%',
    padding: '12px 14px',
    borderRadius: 'var(--radius)',
    border: '1px solid var(--border)',
    background: 'var(--surface)',
    color: 'var(--text)',
    resize: 'vertical',
    minHeight: 64,
  },
  row: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 12 },
  input: {
    flex: '1 1 200px',
    maxWidth: 280,
    padding: '10px 14px',
    borderRadius: 8,
    border: '1px solid var(--border)',
    background: 'var(--bg)',
    color: 'var(--text)',
  },
  btnPrimary: {
    padding: '10px 20px',
    borderRadius: 'var(--radius-sm)',
    border: 'none',
    background: 'var(--accent)',
    color: 'var(--on-accent)',
    fontWeight: 600,
  },
  btnGhost: {
    padding: '8px 14px',
    borderRadius: 8,
    border: '1px solid var(--border)',
    background: 'var(--surface-hover)',
    color: 'var(--text)',
  },
  linkBtn: {
    display: 'inline-block',
    padding: '8px 14px',
    borderRadius: 8,
    border: '1px solid var(--border)',
    background: 'var(--surface-hover)',
    color: 'var(--text)',
    fontSize: 14,
    textDecoration: 'none',
  },
  toolbarBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    padding: 16,
    borderRadius: 'var(--radius)',
    border: '1px solid var(--border)',
    background: 'var(--bg)',
    width: '100%',
    maxWidth: '100%',
  },
  error: {
    marginTop: 16,
    padding: '14px 16px',
    borderRadius: 'var(--radius)',
    borderLeft: '4px solid var(--danger)',
    background: 'var(--danger-soft)',
    color: 'var(--text)',
    fontSize: 14,
  },
  code: { fontSize: 12, padding: '2px 6px', borderRadius: 4, background: 'var(--accent-soft)' },
  codeSmall: { fontSize: 11, cursor: 'pointer' },
  main: { flex: 1, padding: 24 },
  mainToolbar: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 12,
    justifyContent: 'flex-start',
    minHeight: 36,
  },
  mainToolbarRight: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    marginLeft: 'auto',
  },
  metaRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  meta: { fontSize: 13, color: 'var(--text-muted)' },
  toolbarControl: {
    height: 36,
    minHeight: 36,
    padding: '0 14px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border)',
    background: 'var(--surface-hover)',
    color: 'var(--text)',
    fontSize: 13,
    lineHeight: '34px',
    boxSizing: 'border-box',
    cursor: 'pointer',
  },
  sortSelect: {
    height: 36,
    minHeight: 36,
    padding: '0 12px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border)',
    background: 'var(--bg)',
    color: 'var(--text)',
    fontSize: 13,
    boxSizing: 'border-box',
    cursor: 'pointer',
  },
  sortDropdownTrigger: {
    height: 36,
    minHeight: 36,
    padding: '0 12px',
    paddingRight: 28,
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border)',
    background: 'var(--surface-hover)',
    color: 'var(--text)',
    fontSize: 13,
    boxSizing: 'border-box',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    position: 'relative',
    whiteSpace: 'nowrap',
  },
  sortDropdownPanel: {
    position: 'absolute',
    top: '100%',
    left: 0,
    marginTop: 4,
    minWidth: '100%',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border)',
    background: 'var(--surface)',
    boxShadow: 'var(--shadow)',
    zIndex: 100,
    overflow: 'hidden',
  },
  sortDropdownOption: {
    display: 'block',
    width: '100%',
    padding: '8px 12px',
    border: 'none',
    background: 'none',
    color: 'var(--text)',
    fontSize: 13,
    textAlign: 'left',
    cursor: 'pointer',
  },
  batchBar: { display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap', minHeight: 36 },
  batchCount: { fontSize: 13, color: 'var(--text-muted)', lineHeight: '36px' },
  btnDanger: {
    height: 36,
    minHeight: 36,
    padding: '0 16px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--danger)',
    background: 'var(--danger-soft)',
    color: 'var(--danger)',
    cursor: 'pointer',
    fontSize: 13,
    boxSizing: 'border-box',
    lineHeight: '34px',
  },
  btnPrimaryBar: {
    height: 36,
    minHeight: 36,
    padding: '0 16px',
    borderRadius: 'var(--radius-sm)',
    border: 'none',
    background: 'var(--accent)',
    color: 'var(--on-accent)',
    cursor: 'pointer',
    fontSize: 13,
    boxSizing: 'border-box',
    lineHeight: '34px',
  },
  filterInput: {
    flex: '1 1 200px',
    minWidth: 0,
    maxWidth: 280,
    height: 36,
    minHeight: 36,
    padding: '0 14px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border)',
    background: 'var(--bg)',
    color: 'var(--text)',
    fontSize: 13,
    boxSizing: 'border-box',
  },
  zoomRow: { display: 'flex', alignItems: 'center', gap: 6 },
  zoomBtn: {
    width: 36,
    minWidth: 36,
    height: 36,
    minHeight: 36,
    padding: 0,
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    background: 'var(--surface-hover)',
    color: 'var(--text)',
    fontSize: 18,
    lineHeight: 1,
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  settingsBackdrop: { position: 'fixed', inset: 0, zIndex: 10 },
  settingsDropdown: {
    position: 'absolute',
    top: '100%',
    right: 0,
    marginTop: 4,
    minWidth: 140,
    padding: 4,
    borderRadius: 8,
    border: '1px solid var(--border)',
    background: 'var(--surface)',
    boxShadow: 'var(--shadow)',
    zIndex: 11,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  settingsItem: {
    display: 'block',
    width: '100%',
    padding: '8px 12px',
    border: 'none',
    borderRadius: 6,
    background: 'transparent',
    color: 'var(--text)',
    fontSize: 14,
    textAlign: 'left',
    cursor: 'pointer',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(168px, 1fr))',
    gap: 16,
  },
  card: {
    background: 'var(--surface)',
    borderRadius: 'var(--radius)',
    border: '1px solid var(--border)',
    overflow: 'hidden',
    cursor: 'pointer',
    transition: 'transform 0.15s ease, box-shadow 0.15s ease',
    boxShadow: 'var(--shadow)',
    position: 'relative',
  },
  cardSelected: { boxShadow: '0 0 0 2px var(--platform-accent)' },
  cardDragging: { opacity: 0.6, transform: 'scale(0.98)', cursor: 'grabbing' },
  cardDropTarget: {
    boxShadow: '0 0 0 2px var(--platform-accent)',
    background: 'var(--platform-accent-soft)',
  },
  cardActions: {
    position: 'absolute',
    top: 6,
    left: 6,
    display: 'flex',
    alignItems: 'center',
    zIndex: 2,
  },
  cardCheckbox: {
    cursor: 'pointer',
    width: 18,
    height: 18,
    accentColor: 'var(--platform-accent)',
  },
  cardDelete: {
    width: 24,
    height: 24,
    padding: 0,
    borderRadius: 6,
    border: '1px solid var(--border)',
    background: 'var(--surface)',
    color: 'var(--text)',
    fontSize: 16,
    lineHeight: 1,
    cursor: 'pointer',
  },
  thumbWrap: {
    aspectRatio: '3 / 4',
    background: 'var(--bg)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  thumb: { width: '100%', height: '100%', objectFit: 'contain' },
  thumbSkeleton: {
    width: '100%',
    height: '100%',
    minHeight: 60,
    background: 'var(--surface-hover)',
  },
  thumbFailed: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 8,
  },
  thumbFailedText: { fontSize: 12, color: 'var(--text-muted)' },
  thumbRetryBtn: {
    padding: '4px 10px',
    fontSize: 12,
    border: '1px solid var(--border)',
    borderRadius: 6,
    background: 'var(--surface-hover)',
    color: 'var(--text)',
    cursor: 'pointer',
  },
  thumbPlaceholder: { fontSize: 12, color: 'var(--text-muted)', padding: 12 },
  cardBody: { padding: 10 },
  cardName: {
    fontSize: 13,
    fontWeight: 600,
    lineHeight: 1.4,
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    marginBottom: 8,
    color: 'var(--text)',
    textAlign: 'center',
    cursor: 'pointer',
  },
  cardMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  cardMetaRight: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
    flexWrap: 'wrap',
    fontSize: 12,
  },
  cardMetaCenter: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    fontSize: 12,
  },
  copyrightTag: {
    fontSize: 10,
    padding: '1px 6px',
    borderRadius: 4,
    background: 'var(--danger-soft)',
    color: 'var(--danger)',
    fontWeight: 600,
  },
  btnMini: {
    fontSize: 11,
    padding: '2px 8px',
    borderRadius: 4,
    border: '1px solid var(--border)',
    background: 'var(--surface-hover)',
    color: 'var(--text)',
  },
  btnMiniLink: {
    fontSize: 11,
    padding: '2px 8px',
    borderRadius: 4,
    border: '1px solid var(--border)',
    background: 'var(--surface-hover)',
    color: 'var(--text)',
    textDecoration: 'none',
  },
  skeletonGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(168px, 1fr))',
    gap: 16,
  },
  skeletonCard: {
    aspectRatio: '16 / 10',
    borderRadius: 'var(--radius)',
    background:
      'linear-gradient(90deg, var(--surface) 25%, var(--surface-hover) 50%, var(--surface) 75%)',
    backgroundSize: '200% 100%',
    animation: 'shimmer 1.2s ease infinite',
  },
  empty: {
    color: 'var(--text-muted)',
    padding: 48,
    textAlign: 'center',
    fontSize: 15,
    lineHeight: 1.6,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
  },
  emptyMeta: { fontSize: 13, color: 'var(--text-muted)' },
  pre: {
    marginTop: 24,
    padding: 16,
    borderRadius: 'var(--radius)',
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    overflow: 'auto',
    fontSize: 12,
    maxHeight: 400,
  },
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.75)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: 24,
  },
  deleteConfirmModal: {
    background: 'var(--surface)',
    borderRadius: 'var(--radius)',
    border: '1px solid var(--border)',
    boxShadow: 'var(--shadow)',
    padding: 24,
    minWidth: 280,
  },
  deleteConfirmText: { margin: '0 0 20px', fontSize: 15, color: 'var(--text)' },
  deleteConfirmActions: { display: 'flex', justifyContent: 'flex-end', gap: 12 },
  lightbox: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    width: 'fit-content',
    maxWidth: 'min(92vw, 1200px)',
    maxHeight: '90vh',
    background: 'var(--surface)',
    borderRadius: 'var(--radius)',
    overflow: 'hidden',
    boxShadow: 'var(--shadow)',
  },
  closeBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 40,
    height: 40,
    border: 'none',
    borderRadius: '50%',
    background: 'rgba(0,0,0,0.5)',
    color: '#fff',
    fontSize: 24,
    lineHeight: 1,
    zIndex: 1,
  },
  lightboxImg: {
    display: 'block',
    maxWidth: '100%',
    maxHeight: '75vh',
    objectFit: 'contain',
    margin: '0 auto',
  },
  lightboxPlaceholder: { padding: 48, textAlign: 'center', color: 'var(--text-muted)' },
  lightboxCaption: {
    padding: 16,
    borderTop: '1px solid var(--border)',
    fontSize: 14,
    minWidth: 0,
    overflowWrap: 'break-word',
    wordBreak: 'break-word',
  },
  lightboxName: { fontWeight: 600, marginBottom: 8, cursor: 'pointer' },
  lightboxIdRow: { display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  toast: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    padding: '12px 20px',
    borderRadius: 'var(--radius-sm)',
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    boxShadow: 'var(--shadow)',
    zIndex: 9999,
    fontSize: 14,
    animation: 'toastFadeIn 0.2s ease-out',
  },
  embedWrap: { marginBottom: 24 },
  embedHint: { fontSize: 14, color: 'var(--text-muted)', marginBottom: 12 },
  embedFrame: {
    width: '100%',
    minHeight: '85vh',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    background: 'var(--surface)',
  },
  backToTop: {
    position: 'fixed',
    bottom: 24,
    right: 24,
    width: 48,
    height: 48,
    borderRadius: '50%',
    border: '1px solid var(--border)',
    background: 'var(--surface)',
    color: 'var(--text)',
    boxShadow: 'var(--shadow)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 20,
    lineHeight: 1,
    cursor: 'pointer',
    zIndex: 100,
  },
}
